### ISSUE TITLE
No "resource.cgn" file

### ISSUE THREAD

**Issue by amrography** [GDGKuwait/knet-php-demo#1]
Hi 

I tried to run the tool in local host but I got this error:

`Warning: fopen(D:\php\resource\resource.cgn): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/pck/github/com/aciworldwide/commerce/gateway/plugins/e24PaymentPipe.inc.php on line 560`

What is **resource.cgn** file ?

**Comment by msankar1991** [comment]
Hi @amrography , The resource.cgn file will be given Knet payment gateway after your successful registration with their website to you terms applied.

**Comment by shopifymaster007** [comment]
Can i create developer account do you have any idea? or from where i can register?

**Comment by burhan** [comment]
You will get a demo / test resource file once you have registered with the payment processor.

**Comment by ahmed32ali** [comment]
I registered and I have received demo.zip , resource.cgn and pdf file but it full of errors many errors appear and what is the alias.xml file and what it should contain and i got a message failed to connect ? why not to give us a working example ? it's not working at all ?

**Comment by wafaaSultan** [comment]
Hello 
change the path of resource.cgn in buy.php file  as following

$Pipe->setResourcePath("D:\\php\\resource\\"); //change the path where your resource file is

the error will solved
